### ISSUE TITLE
Consolidating review comments 

### ISSUE THREAD

**Issue by nikulkarni** [gkushang/nemo-window#1]
1. When using debug module, putting 'nemo-window' in the log statement is redundant
   [Kushang] agree
2. Not sure why getMainWindowHandle(); is called explicitly?
   [Kushang] Oh yes, I was debugging it and forgot to take it off. Good catch!
3. Don't throw errors from plugin, rather use debug:error to print the error. This will be consistent across nemo plugins
   [Kushang]  Got it!
4. Methods like switchTab, naming is little confusing. I would rename and stick to word window as much as possible
   [Kushang] I used a Tab as like user use TAB to switch between windows.
5. I don't know how newWindow() works. Because it launches a new window and returns a string representation of array of handles and calls switchTab(windowHandle). When you have more than one windows handles passed to switchTab, it will fail. Here you may want to launch new window and switch control to it and simply return.
   [Kushang]  Agree. I did not realize I am returning array of handles. I'll update it
6. `var switchFrame = function (id)`, here change `id` to `nameOrIndex` and loosen up the type check. Underlying WebDriver api supports either name or index.
   [Kushang] Makes sense.
7. Move nemo to peer dependencies from core dependencies.
   [Kushang] will do.
8. Adding tests, examples in a different folder would help users
   [Kushang] I added a example in ReadME. I'll add tests as another PR.
9. Also in `switchTab`, you can't assume that there will always be two windows. If Users have more than two windows then current code will likely switch to an incorrect window
   [Kushang]  switchTab also accepts windowHandle as an argument. If users have more than one window then they have to pass the particular windowHandle and it will switch to particular window. In most of the cases, users will have two windows open (main and pop-up or sub window) and switchTab will make it very easy to switch windows. However, user still has an option to switch to particular window.

**Comment by gkushang** [comment]
resolved, thanks Nilesh !
